const productosArray = [
{  id: "hombres",
    titulo: "Camisa roja Aéro",
    imagen: "./pictures/camisas/camisa_roja_lisa_hombre.jpg",
    categoria: {
        nombre: "Hombres",
        id: "hombres",
    },
    precio: 1000,
},
{ id: "mujeres",
titulo: "Blusa off shoulder",
imagen: "./pictures/camisas/blusa_estampada_flores_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",
},
precio: 2000,
},
{id: "mujeres",
titulo: "Blusa fucsia",
imagen: "./pictures/camisas/blusa_fucsia_mujer.png",
categoria: {
    nombre: "Mujeres",
    id:"mujeres",
},
precio: 2000,
},
{id: "mujeres",
titulo: "Camisa bordó",
imagen: "./pictures/camisas/camisa_bordo_entallada_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",
},
precio: 1000,
},
{id: "niños",
titulo: "Camisa manga corta Jean",
imagen: "./pictures/camisas/camisa_corta_jean_niño.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
},
precio: 500,},
{id: "hombres",
titulo: "camisa escosesa celeste",
imagen: "./pictures/camisa_escosesa_celeste.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",
}, precio: 1500,},{ id: "niños",
titulo: "Camisa Bennetton niña",
imagen: "./pictures/camisas/camisa_estampada_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 500,
},{
    id: "niños",
titulo: "Camisa Grisino dinos",
imagen: "./pictures/camisas/camsisa_estampada_niño.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 500,
},{ id: "niños",
titulo: "Camisa blanca Zara",
imagen: "./pictures/camisas/camisa_lisa_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 500,},{
    id:"hombres",
    titulo: "Camisa manga corta Montagne",
    imagen: "./pictures/camisas/camisa_manga_corta_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",
}, precio: 1000,},
{id: "niños",
titulo: "Camisa manga corta amarilla",
imagen: "./pictures/camisas/camisa_manga_corta_niña.jpeg",
categoria: {
nombre: "Niños",
id:"niños",
}, precio: 500,},
{id: "hombres",
titulo: "Buzo Aéro",
imagen: "./pictures/abrigos/buzo_estampado_hombre.jpg",
categoria: {
nombre: "Hombres",
id:"hombres",
}, precio: 1800,},
{id: "niños",
titulo: "Buzo Spread",
imagen: "./pictures/abrigos/buzo_estampado_niño.jpg",
categoria: {
    nombre:"Niños",
    id: "niños", 
}, precio: 900,
},{
    id: "hombres",
    titulo: "Buzo Negro",
    imagen: "./pictures/abrigos/buzo_liso_hombre.jpg",
    categoria: {
        nombre: "Hombres",
        id: "hombres",
}, precio: 1000,},{
    id:"niños",
    titulo: "Buzo bicolor Montagne",
    imagen: "./pictures/abrigos/buzo_niño_deportivo.jpg",
    categoria: {
        nombre: "Niños",
        id: "niños",
}, precio: 900,},{
id: "niños",
titulo: "Buzo corto Pili",
imagen: "./pictures/abrigos/buzos_cortos_niñas",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 900,},{
    id: "niños",
    titulo: "Buzo niña Happy",
    imagen: "./pictures/abrigo/buzos_estampados_niñas.png",
    categoria: {
        nombre: "Niños",
        id:"niños",
    }, precio: 900,},{
        id: "mujeres",
titulo:"Buzo canguro colores",
imagen: "./pictures/abrigos/buzos_lisos_mujer.jpeg",
categoria: {
    nombre: "Mujeres",
id: "mujeres",}, precio: 1800},{
    id: "hombres",
    titulo: "Campera de abrigo Max",
    imagen: "./pictures/abrigos/campera_abrigo_hombre.jpg",
    categoria: {
        nombre: "Hombres",
        id:"hombres",}, precio: 2000,},
{id:"mujeres",
titulo: "Campera de abrigo Barbie",
imagen: "./pictures/abrigos/campera_abrigo_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 2000,},{
id: "niños",
titulo: "Campera de abrigo Alex",
imagen: "./pictures/abrigos/campera_abrigo_unisex_niños.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 1400,},
{id: "mujeres",
titulo: "Campera deportiva Adidas",
imagen: "./pictures/abrigos/campera_adidas_deportiva_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",},precio: 1600,},
{id :"hombres",
titulo: "Campera deportiva negra",
imagen: "./pictures/abrigos/campera_deportiva_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",
}, precio: 1600,},{
id:"mujeres",
titulo: "Sweater bordado Flor",
imagen: "./pictures/abrigos/sweater_bordado_mujer.jpg",
categoria:{
    nombre: "Mujeres",
    id: "mujeres",}, precio: 2000,},
{id: "hombres",
titulo: "Sweater Negro",
imagen: "./pictures/abrigos/sweater_liso_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",},precio: 1900,},{
        id:"mujeres",
        titulo: "Sweater Netflix",
        imagen: "./pictures/abrigos/sweater_liso_mujer.jpg",
        categoria: {
            nombre: "Mujeres",
            id: "mujeres,"}, precio: 1900,},
{ id: "mujeres",
titulo: "Sweater rayado Cindy",
imagen: "./pictures/abrigos/sweater_rayado_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 1850,},{
id: "hombres",
titulo: "Sweater rombos",
imagen: "./pictures/abrigos/sweater_rombos_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres,"}, precio: 1850,},
{id:"bebés",
titulo: "Baberos estampados",
imagen: "./pictures/accesorios/baberos_bebe.jpeg",
categoria:{
nombre: "Bebés",
id: "bebés",}, precio: 100,},
{id: "mujeres",
titulo: "Bandolera verde Studio F",
imagen: "./pictures/accesorios/bandolera_mujer.jpg",
categoria: {
    nombre:"Mujeres",
    id: "mujeres",}, precio: 200,},
{id: "hombres",
    titulo: "Cinturon negro",
    imagen: "./pictures/accesorios/cinturon_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 550,},
{id:"mujeres",
titulo: "Cinturón Flora",
imagen: "./pictures/accesorios/cinturon_mujer.png",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio:550,},
{id: "bebés",
titulo: "Conjunto gorrito + mitones varios colores",
imagen: "./pictures/accesorios/conjunto_gorros_mitones_bebe.jpg",
categoria:{
    nombre: "Bebés",
    id: "bebés",}, precio: 120,},
{id: "mujeres",
titulo: "Scrunchies x4 colores varios",
imagen: "./pictures/accesorios/gomitas_pelo_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 100,},
{id: "niños",
titulo: "Gomitas coloridas",
imagen: "./pictures/accesorios/gomitas_pelo_niña.jpg",
categoria: {
nombre:"Niños",
id: "niños",}, precio: 50,},
{id: "niños",
titulo: "Gorra rosa Zara",
imagen: "./pictures/accesorios/gorra_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 200,},
{id: "hombres",
nombre: "Gorra rojo y azul",
imagen: ".pictures/accesorios/gorra_zara_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 200,},
{id: "bebés",
titulo: "Gorro UV naranja bebé",
imagen: "./pictures/accesorios/gorro_uv_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 200,},
{id: "niños",
titulo: "Hebillitas con rositas X12 varios colores",
imagen: "./pictures/accesorios/habillas_pelo_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 50,},
{id: "hombres",
titulo: "Pares de medias estamapadas Man",
imagen: "./pictures/accesorios/medias_estampadas_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 60,},
{id: "mujeres",
titulo: "Pares de medias estampadas Woman",
imagen: "./pictures/accesorios/medias_estampadas_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 60,},
{id: "niños",
titulo: "Pares de medias estampadas Kids",
imagen: "./pictures/accesorios/medias_estampadas_niños.jpg",
categoria: {
nombre: "Niños",
id: "niños",}, precio: 60,},
{id: "niños",
titulo: "Mochila Zara",
imagen: "./pictures/accesorios/mochila_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 80,},
{id: "mujeres",
titulo: "Pañuelo estampado",
imagen: "./pictures/accesorios/pañuelo_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 90,},
{id: "hombres",
titulo: "Pulseras árbol",
imagen: "./pictures/accesorios/pulsera_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 85,},
{id: "mujeres",
titulo: "Pulseras rose gold",
imagen: "./pictures/accesorios/pulsera_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 95,},
{id: "hombre",
titulo: "Reloj negro Massimo",
imagen: "./pictures/accesorios/reloj_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 120,},
{id: "mujeres",
titulo: "Sombrero Crudo",
imagen: "./pictures/accesorios/sombrero_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 140,},
{id: "bebés",
titulo: "Vincha moño Mona",
imagen: "./pictures/accesorios/vincha_moños_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 55,},
{id: "niños",
titulo: "Vinchas Vichy",
imagen: "./pictures/accesorios/vincha_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 60,},
{id: "bebés",
titulo: "Bodys Bebé rosa",
imagen: "./pictures/bebe/body_bebe_estampados_niña.jpeg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id: "bebés",
titulo: "Bodys Animalitos",
imagen: "./pictures/bebe/bodys_bebe_estampa.png",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id: "bebés",
titulo: "Bodys Celeste",
imagen: "./pictures/bebe/bodys_bebe_estampados_niños.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id: "bebés",
titulo: "Bodys color",
imagen: "./pictures/bebe/bodys_bebe_lisos.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id:"bebés",
titulo: "Buzo conejitos",
imagen: "./pictures/bebe/buzo_bebe_niña.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 500,},
{id: "bebés",
titulo: "Buzo zoo",
imagen: "./pictures/bebe/buzo_estampado_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 500,},
{id: "bebés",
titulo: "Conjunto ositos",
imagen: "./pictures/bebe/conjunto_bebe_animalitos.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",},precio: 450,}, 
{id: "bebés",
titulo: "Conjunto volados",
imagen: "./pictures/bebe/conjunto_bebe_volados.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 450,},
{id: "bebés",
titulo: "Medias estamapadas corderito",
imagen: "./pictures/bebe/medias_bebe_corderito.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 150,},
{id: "bebés",
titulo: "medias antideslizantes",
imagen: "./pictures/bebe/medias_bebe_estampadas_antideslisantes.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 150,},
{id: "bebés",
titulo: "Medias bebé pastel",
imagen: "./pictures/bebe/medias_bebe_pastel.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 150,},
{id: "mujeres",
titulo: "Botas bordadas Chealsea",
imagen: "./pictures/calzado/botas_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 2500,},
{id: "niños",
titulo: "Botín Cordelia",
imagen: "./pictures/calzado/botin_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 2500,},
{id: "niños",
titulo: ""}
]