const productosArray = [
{  id: "hombres",
    titulo: "Camisa roja Aéro",
    imagen: "./pictures/camisas/camisa_roja_lisa_hombre.jpg",
    categoria: {
        nombre: "Hombres",
        id: "hombres",
    },
    precio: 1000,
},
{ id: "mujeres",
titulo: "Blusa off shoulder",
imagen: "./pictures/camisas/blusa_estampada_flores_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",
},
precio: 2000,
},
{id: "mujeres",
titulo: "Blusa fucsia",
imagen: "./pictures/camisas/blusa_fucsia_mujer.png",
categoria: {
    nombre: "Mujeres",
    id:"mujeres",
},
precio: 2000,
},
{id: "mujeres",
titulo: "Camisa bordó",
imagen: "./pictures/camisas/camisa_bordo_entallada_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",
},
precio: 1000,
},
{id: "niños",
titulo: "Camisa manga corta Jean",
imagen: "./pictures/camisas/camisa_corta_jean_niño.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
},
precio: 500,},
{id: "hombres",
titulo: "camisa escosesa celeste",
imagen: "./pictures/camisa_escosesa_celeste.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",
}, precio: 1500,},{ id: "niños",
titulo: "Camisa Bennetton niña",
imagen: "./pictures/camisas/camisa_estampada_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 500,
},{
    id: "niños",
titulo: "Camisa Grisino dinos",
imagen: "./pictures/camisas/camsisa_estampada_niño.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 500,
},{ id: "niños",
titulo: "Camisa blanca Zara",
imagen: "./pictures/camisas/camisa_lisa_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 500,},{
    id:"hombres",
    titulo: "Camisa manga corta Montagne",
    imagen: "./pictures/camisas/camisa_manga_corta_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",
}, precio: 1000,},
{id: "niños",
titulo: "Camisa manga corta amarilla",
imagen: "./pictures/camisas/camisa_manga_corta_niña.jpeg",
categoria: {
nombre: "Niños",
id:"niños",
}, precio: 500,},
{id: "hombres",
titulo: "Buzo Aéro",
imagen: "./pictures/abrigos/buzo_estampado_hombre.jpg",
categoria: {
nombre: "Hombres",
id:"hombres",
}, precio: 1800,},
{id: "niños",
titulo: "Buzo Spread",
imagen: "./pictures/abrigos/buzo_estampado_niño.jpg",
categoria: {
    nombre:"Niños",
    id: "niños", 
}, precio: 900,
},{
    id: "hombres",
    titulo: "Buzo Negro",
    imagen: "./pictures/abrigos/buzo_liso_hombre.jpg",
    categoria: {
        nombre: "Hombres",
        id: "hombres",
}, precio: 1000,},{
    id:"niños",
    titulo: "Buzo bicolor Montagne",
    imagen: "./pictures/abrigos/buzo_niño_deportivo.jpg",
    categoria: {
        nombre: "Niños",
        id: "niños",
}, precio: 900,},{
id: "niños",
titulo: "Buzo corto Pili",
imagen: "./pictures/abrigos/buzos_cortos_niñas",
categoria: {
    nombre: "Niños",
    id: "niños",
}, precio: 900,},{
    id: "niños",
    titulo: "Buzo niña Happy",
    imagen: "./pictures/abrigo/buzos_estampados_niñas.png",
    categoria: {
        nombre: "Niños",
        id:"niños",
    }, precio: 900,},{
        id: "mujeres",
titulo:"Buzo canguro colores",
imagen: "./pictures/abrigos/buzos_lisos_mujer.jpeg",
categoria: {
    nombre: "Mujeres",
id: "mujeres",}, precio: 1800},{
    id: "hombres",
    titulo: "Campera de abrigo Max",
    imagen: "./pictures/abrigos/campera_abrigo_hombre.jpg",
    categoria: {
        nombre: "Hombres",
        id:"hombres",}, precio: 2000,},
{id:"mujeres",
titulo: "Campera de abrigo Barbie",
imagen: "./pictures/abrigos/campera_abrigo_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 2000,},{
id: "niños",
titulo: "Campera de abrigo Alex",
imagen: "./pictures/abrigos/campera_abrigo_unisex_niños.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 1400,},
{id: "mujeres",
titulo: "Campera deportiva Adidas",
imagen: "./pictures/abrigos/campera_adidas_deportiva_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",},precio: 1600,},
{id :"hombres",
titulo: "Campera deportiva negra",
imagen: "./pictures/abrigos/campera_deportiva_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",
}, precio: 1600,},{
id:"mujeres",
titulo: "Sweater bordado Flor",
imagen: "./pictures/abrigos/sweater_bordado_mujer.jpg",
categoria:{
    nombre: "Mujeres",
    id: "mujeres",}, precio: 2000,},
{id: "hombres",
titulo: "Sweater Negro",
imagen: "./pictures/abrigos/sweater_liso_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",},precio: 1900,},{
        id:"mujeres",
        titulo: "Sweater Netflix",
        imagen: "./pictures/abrigos/sweater_liso_mujer.jpg",
        categoria: {
            nombre: "Mujeres",
            id: "mujeres,"}, precio: 1900,},
{ id: "mujeres",
titulo: "Sweater rayado Cindy",
imagen: "./pictures/abrigos/sweater_rayado_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 1850,},{
id: "hombres",
titulo: "Sweater rombos",
imagen: "./pictures/abrigos/sweater_rombos_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres,"}, precio: 1850,},
{id:"bebés",
titulo: "Baberos estampados",
imagen: "./pictures/accesorios/baberos_bebe.jpeg",
categoria:{
nombre: "Bebés",
id: "bebés",}, precio: 100,},
{id: "mujeres",
titulo: "Bandolera verde Studio F",
imagen: "./pictures/accesorios/bandolera_mujer.jpg",
categoria: {
    nombre:"Mujeres",
    id: "mujeres",}, precio: 200,},
{id: "hombres",
    titulo: "Cinturon negro",
    imagen: "./pictures/accesorios/cinturon_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 550,},
{id:"mujeres",
titulo: "Cinturón Flora",
imagen: "./pictures/accesorios/cinturon_mujer.png",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio:550,},
{id: "bebés",
titulo: "Conjunto gorrito + mitones varios colores",
imagen: "./pictures/accesorios/conjunto_gorros_mitones_bebe.jpg",
categoria:{
    nombre: "Bebés",
    id: "bebés",}, precio: 120,},
{id: "mujeres",
titulo: "Scrunchies x4 colores varios",
imagen: "./pictures/accesorios/gomitas_pelo_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 100,},
{id: "niños",
titulo: "Gomitas coloridas",
imagen: "./pictures/accesorios/gomitas_pelo_niña.jpg",
categoria: {
nombre:"Niños",
id: "niños",}, precio: 50,},
{id: "niños",
titulo: "Gorra rosa Zara",
imagen: "./pictures/accesorios/gorra_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 200,},
{id: "hombres",
nombre: "Gorra rojo y azul",
imagen: ".pictures/accesorios/gorra_zara_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 200,},
{id: "bebés",
titulo: "Gorro UV naranja bebé",
imagen: "./pictures/accesorios/gorro_uv_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 200,},
{id: "niños",
titulo: "Hebillitas con rositas X12 varios colores",
imagen: "./pictures/accesorios/habillas_pelo_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 50,},
{id: "hombres",
titulo: "Pares de medias estamapadas Man",
imagen: "./pictures/accesorios/medias_estampadas_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 60,},
{id: "mujeres",
titulo: "Pares de medias estampadas Woman",
imagen: "./pictures/accesorios/medias_estampadas_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 60,},
{id: "niños",
titulo: "Pares de medias estampadas Kids",
imagen: "./pictures/accesorios/medias_estampadas_niños.jpg",
categoria: {
nombre: "Niños",
id: "niños",}, precio: 60,},
{id: "niños",
titulo: "Mochila Zara",
imagen: "./pictures/accesorios/mochila_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 80,},
{id: "mujeres",
titulo: "Pañuelo estampado",
imagen: "./pictures/accesorios/pañuelo_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 90,},
{id: "hombres",
titulo: "Pulseras árbol",
imagen: "./pictures/accesorios/pulsera_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 85,},
{id: "mujeres",
titulo: "Pulseras rose gold",
imagen: "./pictures/accesorios/pulsera_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 95,},
{id: "hombre",
titulo: "Reloj negro Massimo",
imagen: "./pictures/accesorios/reloj_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 120,},
{id: "mujeres",
titulo: "Sombrero Crudo",
imagen: "./pictures/accesorios/sombrero_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 140,},
{id: "bebés",
titulo: "Vincha moño Mona",
imagen: "./pictures/accesorios/vincha_moños_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 55,},
{id: "niños",
titulo: "Vinchas Vichy",
imagen: "./pictures/accesorios/vincha_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 60,},
{id: "bebés",
titulo: "Bodys Bebé rosa",
imagen: "./pictures/bebe/body_bebe_estampados_niña.jpeg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id: "bebés",
titulo: "Bodys Animalitos",
imagen: "./pictures/bebe/bodys_bebe_estampa.png",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id: "bebés",
titulo: "Bodys Celeste",
imagen: "./pictures/bebe/bodys_bebe_estampados_niños.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id: "bebés",
titulo: "Bodys color",
imagen: "./pictures/bebe/bodys_bebe_lisos.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 400,},
{id:"bebés",
titulo: "Buzo conejitos",
imagen: "./pictures/bebe/buzo_bebe_niña.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 500,},
{id: "bebés",
titulo: "Buzo zoo",
imagen: "./pictures/bebe/buzo_estampado_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 500,},
{id: "bebés",
titulo: "Conjunto ositos",
imagen: "./pictures/bebe/conjunto_bebe_animalitos.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",},precio: 450,}, 
{id: "bebés",
titulo: "Conjunto volados",
imagen: "./pictures/bebe/conjunto_bebe_volados.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 450,},
{id: "bebés",
titulo: "Medias estamapadas corderito",
imagen: "./pictures/bebe/medias_bebe_corderito.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 150,},
{id: "bebés",
titulo: "medias antideslizantes",
imagen: "./pictures/bebe/medias_bebe_estampadas_antideslisantes.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 150,},
{id: "bebés",
titulo: "Medias bebé pastel",
imagen: "./pictures/bebe/medias_bebe_pastel.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 150,},
{id: "mujeres",
titulo: "Botas bordadas Chealsea",
imagen: "./pictures/calzado/botas_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 2500,},
{id: "niños",
titulo: "Botín Cordelia",
imagen: "./pictures/calzado/botin_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 2500,},
{id: "niños",
titulo: "Mocasín Nino",
imagen: "./pictures/calzado/mocasin_niño.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 2000,},
{id: "mujeres",
titulo: "Ojotas Adidas",
imagen:"./pictures/calzado/ojotas_adidas_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 1900,},
{id: "niños",
titulo: "Zapato Guillermina",
imagen:"./pictures/calzado/guillerminas_colores_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 2000,},
{id: "bebés",
titulo: "Ojota panda bebé",
imagen: "./pictures/calzado/ojotas_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 1800,},
{id: "hombres",
titulo: "Ojota Simli",
imagen: "./pictures/calzado/ojotas_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 1800,},
{id: "niños",
titulo: "Ojotas Princesas",
imagen: "./pictures/calzado/ojotas_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 1800,},
{id: "niños",
titulo: "Ojotas Comic",
imagen: "./pictures/calzado/ojotas_niño.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 1800,},
{id: "mujeres",
titulo: "Sandalias Vera",
imagen: "./pictures/calzado/sanadalias_fucsia_mujer.jpg",
categoria: {
nombre: "Mujeres",
id: "mujeres",}, precio: 1850,},
{id: "niños",
titulo: "Sandalias Paloma ",
imagen: "./pictures/calzado/sandalias_rosa_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 1750,},
{id: "mujeres",
titulo: "Stiletto Siyah ",
imagen: "./pictures/calzado/tacos_negros_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 1750,},
{id:"bebés",
titulo:"Zapatillas Renk",
imagen: "./pictures/calzado/zapatillas_bebe.jpg",
categoria: {
    nombre: "Bebés",
    id: "bebés",}, precio: 1300,},
{id:"niños",
titulo:"Zapatillas deportivas IV",
imagen: "./pictures/calzado/zapatillas_deportivas_niños.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 1400,},
{id:"hombres",
id:"mujeres",
    titulo:"Zapatillas deportivas Nike",
    imagen: "./pictures/calzado/Zapatillas_Nike_adultos.jpg",
    categoria: {
        nombre: "Hombres",
        nombre:"Mujeres",
        id: "hombres",
    id: "mujeres",}, precio: 1450,},
{id:"niños",
titulo:"Zapatillas puntera",
imagen: "./pictures/calzado/zapatillas_niños_con_puntera.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 1400,},
{id: "hombres",
titulo: "Zapatillas Narrow",
imagen: "./pictures/calzado/zapatillas_urbanas_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 1450,},
{id: "mujeres",
titulo: "Zapatillas Camel",
imagen: "./pictures/calzado/zapatillas_urbanas_mujer.jpg",
categoria: {
    nombre:"Mujeres",
    id:"mujeres",}, precio: 1455,},
{id: "niños",
titulo: "Jean Cheeky",
imagen: "./pictures/pantalones/jean_cheecky_niño.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 550,},
{id: "mujeres",
titulo: "Jean tiro alto",
imagen: "./pictures/pantalones/jean_tiro_alto_mujer.jpg",
categoria: {
    nombre: "Mujeres",
    id: "mujeres",}, precio: 1500,},
{id: "hombres",
titulo: "Jean tiro bajo",
imagen:"./pictures/pantalones/jeans_hombre.jpg",
categoria: {
    nombre: "Hombres",
    id: "hombres",}, precio: 1500,},
{id: "niños",
titulo: "Jogging Lunares",
imagen: "./pictures/pantalones/joggin__lunares_oshkosh_niña.jpg",
categoria: {
    nombre: "Niños",
    id: "niños",}, precio: 550,},
{id: "mujeres",
titulo: "Jogging Blacky",
imagen: "./pictures/pantalones/jogging_liso_deportivo_mujer.jpg",
categoria: {nombre:"Mujeres", id: "mujeres",}, precio: 1450,},
{id:"mujeres",
titulo:"Palazzo Tiger",
imagen:"./pictures/pantalones/palazzo_estampado_mujer.jpg",
categoria:{nombre: "Mujeres", id:"mujeres",}, precio: 1600,},
{id:"hombres",
titulo:"Pantalón gabardina",
imagen: "./pictures/pantalones/pantalon_beige_hombre.jpg",
categoria: {nombre: "Hombres", id:"hombres",}, precio: 1550},
{id: "hombres",
titulo: "Pantalón Gris",
imagen: "./pictures/pantalones/pantalon_hombre_gris.jpg",
categoria: {nombre:"Hombres", id:"hombres",}, precio: 1550,},
{id:"niños", titulo: "Pantalón mono", imagen: "./pictures/pantalones/pantalon_mono_niños.png",
categoria: { nombre: "Niños", id:"niños",}, precio: 550,},
{id: "hombres", titulo: "Pantalón negro Work", imagen: "./pictures/pantalones/pantalon_negro_hombre.jpg",
categoria: { nombre: "Hombres", id: "hombres",}, precio: 1550,},
{id: "niños", titulo:"Pantalón Granate Little Akiabara", imagen: "./pictures/pantalones/pantalon_ñiña_little_akiabara.jpg",
categoria: { nombre: "Niños", id: "niños",}, precio: 800,},
{id: "mujeres", titulo: "Pantalón Sastrero", imagen: "./pictures/pantalones/pantalon_sastrero_verde_mujer.jpg",
categoria: { nombre:"Mujeres", id:"mujeres",}, precio: 1600,},
{id:"niños", titulo:"Jean oxford Zara", imagen: "./pictures/pantalones/vaqueros_zara_niña.jpg",
categoria: { nombre: "Niños", id: "niños",}, precio: 800,},
{id: "niños", titulo:"Pollera Cora", imagen:"./pictures/polleras/falda_niñas.jpg",
categoria: {nombre: "Niños", id: "niños",}, precio: 600,},
{id: "mujeres", titulo:"Minifalda Party", imagen: "./pictures/polleras/minifalda_negra_mujer.jpg",
categoria: { nombre: "Mujeres", id:"mujeres",}, precio: 1000,},
{id: "mujeres", titulo: "Pollera Urban", imagen:"./pictures/polleras/pollera_deportiva_adidas.jpg",
categoria: { nombre:"Mujeres", id:"mujeres",}, precio: 1000,},
{id: "mujeres", titulo: "Pollera jean Bea", imagen: "./pictures/polleras/pollera_jean_mujer.jpeg",
categoria: { nombre: "Mujeres", id: "mujeres",}, precio: 1000,},
{id: "mujeres", titulo:"Pollera Lápiz Crema", imagen:"./pictures/polleras/pollera_lapiz_crema_mujer.jpg",
categoria: { nombre: "Mujeres", id:"mujeres",}, precio: 1500,},
{id:"mujeres", titulo: "Pollera larga Cebra", imagen:"./pictures/polleras/pollera_larga_zebra_estampada_mujer.jpg",
categoria: {nombre: "Mujeres",id:"mujeres",}, precio: 1500,},
{id: "niños", titulo: "Pollera deportiva Sonder",imagen: "./pictures/polleras/pollera_pantalon_deportiva_niña.jpg",
categoria: {nombre:"Niños",id:"niños",}, precio: 800,},
{id:"mujeres", titulo: "Pollera volados Flopy",imagen:"./pictures/polleras/pollera_summer_negro_mujer.jpg",
categoria: {nombre:"Mujeres",id:"mujeres",},precio: 1500,},
{id:"hombres", titulo:"Remera Pierce",imagen:"./pictures/remeras/remera-de-mujer-pierce.jpg",
categoria: {nombre:"Mujeres",id:"mujeres",},precio: 1000,},
{id: "mujeres",titulo:"Remera Arabesque",imagen:"./pictures/remeras/remera-manga-larga-de-mujer-arabesque.jpg",
categoria: {nombre:"Mujeres",id:"mujeres",},precio:1000,},
{id:"hombres",titulo:"Remera Azur",imagen:"./pictures/remeras/remera_azul_hombre.jpg",
categoria:{nombre:"Hombres",id:"hombres",},precio:1000,},
{id:"mujeres",titulo:"Remera Silueta",imagen:"./pictures/remeras/remera_estampada_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio: 1000,},
{id:"niños",titulo:"Remera Chicas Superpoderosas",imagen:"./pictures/remeras/remera_estampada_niña.jpg",
categoria:{nombre:"Niños",id:"niños",},precio: 500,},
{id:"mujeres",titulo:"Remera Jaspeada",imagen:"./pictures/remeras/remera_gris_bordada_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio:2000,},
{id:"hombres",titulo:"Remera Henley",imagen:"./pictures/remeras/remera_henley_hombre.jpg",
categoria:{nombre:"Hombres",id:"hombres",},precio: 1500,},
{id:"mujeres",titulo:"Remera Blur",imagen:"./pictures/remeras/remera_manga_larga_lisa_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio:1000,},
{id:"niños",titulo:"Remera Bonnie",imagen:"./pictures/remeras/remera_niña_manga_larga_bonie.jpg",
categoria: {nombre:"Niños",id:"niños",},precio:650,},
{id:"niños",titulo:"Remera Scooby",imagen:"./pictures/remeras/remera_niños_scooby_doo.jpg",
categoria:{nombre:"Niños",id:"niños",},precio:650,},
{id:"niños",titulo:"Remera Búho",imagen:"./pictures/remeras/remera_owl_niño_manga_larga.jpg",
categoria:{nombre:"Niños",id:"niños",},precio:650,},
{id:"hombres",titulo:"Remera Teddy",imagen:"./pictures/remeras/remera_roja_hombre.jpg",
categoria:{nombre:"Hombres",id:"hombres",},precio:1000,},
{id:"hombres",titulo:"Remera Salty",imagen:"./pictures/remeras/remera_salty_water_hombre.jpg",
categoria:{nombre:"Hombres",id:"hombres",},precio:1000,},
{id:"hombres",titulo:"Remera Tropic",imagen:"./pictures/remeras/remera_tropic_waves_hombre.jpg",
categoria:{nombre:"Hombres",id:"hombres",},precio:1000,},
{id:"mujeres",titulo:"Remera Lisa",imagen:"./pictures/remeras/remeras_lisas_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio:1000,},
{id:"niños",titulo:"Remera Volados",imagen:"./pictures/remeras/remeras_lisas_niñas.jpg",
categoria:{nombre:"Niños",id:"niños",},precio:600,},
{id:"niños",titulo:"remeras Colors",imagen:"./pictures/remeras/remeras_lisas_niño.jpg",
categoria:{nombre:"Niños",id:"niños",},precio:500,},
{id:"mujeres",titulo:"Vestido Flowers",imagen:"./pictures/vestidos/vestido_corto_estampado_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio:1500,},
{id:"mujeres",titulo:"Vestido Hi-Low",imagen:"./pictures/vestidos/vestido_corto_liso_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio:1500,},
{id:"mujeres",titulo:"Vestido largo Apricot",imagen:"./pictures/vestidos/vestido_largo_estampado_apricot_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio:2000,},
{id:"mujeres",titulo:"Vestido largo Italia",imagen:"./pictures/vestidos/vestido_largo_liso_colores_mujer.jpg",
categoria:{nombre:"Mujeres",id:"mujeres",},precio:2000,},
{id:"niños",titulo:"Vestidos Fanny",imagen:"./pictures/vestidos/vestidos_estampados_niñas.jpg",
categoria:{nombre:"Niños",id:"niños",},precio:950,},
{id:"niños",titulo:"Vestido Lavanda",imagen:"./pictures/vestidos/vestido_asismetrico_popelin_niña.jpg",
categoria:{nombre:"Niños",id:"niños",},precio:950,},
];

const contenedorProductos = document.querySelector("#contenedor-productos");

function cargarProductos (){

productos.forEach(productos => {

    const div = document.createElement("div");
div.classList.add("producto");
div.innerHTML =  ` <img class="producto-imagen" src="${producto.imagen}"
alt="${producto.titulo}">
<div class="producto-detalles">
<h3 class="producto-titulo">${producto.titulo}</h3>
<p class="producto-precio">${producto.precio}</p>
<button class="producto-agregar" id="${producto.id}">Agregar</button>
</div>´;
contenedorProductos.append(div);
})

}
cargarProductos();